###
GET http://localhost:8901/api/chat/with-tools?
    message="123456789的平方根是多少"

###

GET http://localhost:8901/api/chat/with-easy-rag?
    message=“极简说明：怎么学Java”

<> 2025-10-22T214316.200.txt

###
GET http://localhost:8901/api/chat/with-mcp?
    message="今日大事"

###
GET http://localhost:8901/api/chat/with-guardrails?
    message="kill the game"