spring:
  application:
    name: lc4j-demo
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306?useInformationSchema=true&characterEncoding=utf-8  # TODO: 修改为你的数据库URL
    username: root
    password: 123456
  # Redis配置
  data:
    redis:
      host: localhost     # TODO
      port: 6379
      database: 0
      timeout: 3000
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
  
langchain4j:
  open-ai:
    chat-model:
      api-key: sk-abcdxxxxxxxxxxxxxxxxx   # TODO: 替换成你的apikey 北京APIKEY申请:https://bailian.console.aliyun.com/?tab=model&spm=0.0.0.i1#/api-key
      model-name: qwen-max
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      log-requests: true
      log-responses: true
# 为方便测试MCP功能https://mcp.so/server/zhipu-web-search/BigModel?tab=content, 引入智谱AI的MCP服务 https://www.bigmodel.cn/usercenter/proj-mgmt/apikeys
bigmodel:
  api-key: 657f084907174e1693da7a2e7f8615dc.4etNrOB87OqW7hnC

server:
  port: 8901
  servlet:
    context-path: /api  # API前缀，文档地址 http://localhost:8901/api/doc.html || http://localhost:8901/api/v3/api-docs


# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.djchan.lcfjdemo.controller  # TODO: 修改为你的controller路径
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    com.djchan.lcfjdemo.ai.config: DEBUG
    org.springframework.data.redis: DEBUG
    root: INFO